INSERT INTO dogwalkers.pasma (ID_pasma,Pasma_ime,Temperament,WikiPasmeUrl,Visina,Teza) VALUES
	 (1,'Affenpinscher','Stubborn, Curious, Playful, Adventurous, Active, Fun-loving',NULL,'23 - 29','3 - 6'),
	 (2,'Afghan Hound','Aloof, Clownish, Dignified, Independent, Happy',NULL,'64 - 69','23 - 27'),
	 (3,'African Hunting Dog','Wild, Hardworking, Dutiful',NULL,'76','20 - 30'),
	 (4,'Airedale Terrier','Outgoing, Friendly, Alert, Confident, Intelligent, Courageous',NULL,'53 - 58','18 - 29'),
	 (5,'Akbash Dog','Loyal, Independent, Intelligent, Brave',NULL,'71 - 86','41 - 54'),
	 (6,'Akita','Docile, Alert, Responsive, Dignified, Composed, Friendly, Receptive, Faithful, Courageous',NULL,'61 - 71','29 - 52'),
	 (7,'Alapaha Blue Blood Bulldog','Loving, Protective, Trainable, Dutiful, Responsible',NULL,'46 - 61','25 - 41'),
	 (8,'Alaskan Husky','Friendly, Energetic, Loyal, Gentle, Confident',NULL,'58 - 66','17 - 23'),
	 (9,'Alaskan Malamute','Friendly, Affectionate, Devoted, Loyal, Dignified, Playful',NULL,'58 - 64','29 - 45'),
	 (10,'American Bulldog','Friendly, Assertive, Energetic, Loyal, Gentle, Confident, Dominant',NULL,'56 - 69','27 - 54');
INSERT INTO dogwalkers.pasma (ID_pasma,Pasma_ime,Temperament,WikiPasmeUrl,Visina,Teza) VALUES
	 (11,'American Bully','Strong Willed, Stubborn, Friendly, Clownish, Affectionate, Loyal, Obedient, Intelligent, Courageous',NULL,'36 - 43','14 - 68'),
	 (12,'American Eskimo Dog','Friendly, Alert, Reserved, Intelligent, Protective',NULL,'38 - 48','9 - 18'),
	 (13,'American Eskimo Dog (Miniature)','Friendly, Alert, Reserved, Intelligent, Protective',NULL,'23 - 30','3 - 5'),
	 (14,'American Foxhound','Kind, Sweet-Tempered, Loyal, Independent, Intelligent, Loving',NULL,'53 - 71','29 - 34'),
	 (15,'American Pit Bull Terrier','Strong Willed, Stubborn, Friendly, Clownish, Affectionate, Loyal, Obedient, Intelligent, Courageous',NULL,'43 - 53','14 - 27'),
	 (16,'American Staffordshire Terrier','Tenacious, Friendly, Devoted, Loyal, Attentive, Courageous',NULL,'43 - 48','23 - 27'),
	 (17,'American Water Spaniel','Friendly, Energetic, Obedient, Intelligent, Protective, Trainable',NULL,'38 - 46','11 - 20'),
	 (18,'Anatolian Shepherd Dog','Steady, Bold, Independent, Confident, Intelligent, Proud',NULL,'69 - 74','36 - 68'),
	 (19,'Appenzeller Sennenhund','Reliable, Fearless, Energetic, Lively, Self-assured',NULL,'51 - 56','22 - 25'),
	 (21,'Australian Cattle Dog','Cautious, Energetic, Loyal, Obedient, Protective, Brave',NULL,'43 - 51','20 - 28');
INSERT INTO dogwalkers.pasma (ID_pasma,Pasma_ime,Temperament,WikiPasmeUrl,Visina,Teza) VALUES
	 (22,'Australian Kelpie','Friendly, Energetic, Alert, Loyal, Intelligent, Eager',NULL,'43 - 51','14 - 21'),
	 (23,'Australian Shepherd','Good-natured, Affectionate, Intelligent, Active, Protective',NULL,'46 - 58','16 - 29'),
	 (24,'Australian Terrier','Spirited, Alert, Loyal, Companionable, Even Tempered, Courageous',NULL,'25 - 28','6 - 7'),
	 (25,'Azawakh','Aloof, Affectionate, Attentive, Rugged, Fierce, Refined',NULL,'58 - 74','15 - 25'),
	 (26,'Barbet','Obedient, Companionable, Intelligent, Joyful',NULL,'51 - 66','18 - 29'),
	 (28,'Basenji','Affectionate, Energetic, Alert, Curious, Playful, Intelligent',NULL,'41 - 43','10 - 11'),
	 (29,'Basset Bleu de Gascogne','Affectionate, Lively, Agile, Curious, Happy, Active',NULL,'33 - 38','16 - 18'),
	 (30,'Basset Hound','Tenacious, Friendly, Affectionate, Devoted, Sweet-Tempered, Gentle',NULL,'36','23 - 29'),
	 (31,'Beagle','Amiable, Even Tempered, Excitable, Determined, Gentle, Intelligent',NULL,'33 - 38','9 - 16'),
	 (32,'Bearded Collie','Self-confidence, Hardy, Lively, Alert, Intelligent, Active',NULL,'51 - 56','20 - 25');
INSERT INTO dogwalkers.pasma (ID_pasma,Pasma_ime,Temperament,WikiPasmeUrl,Visina,Teza) VALUES
	 (33,'Beauceron','Fearless, Friendly, Intelligent, Protective, Calm',NULL,'61 - 70','36 - 50'),
	 (34,'Bedlington Terrier','Affectionate, Spirited, Intelligent, Good-tempered',NULL,'38 - 41','8 - 10'),
	 (36,'Belgian Malinois','Watchful, Alert, Stubborn, Friendly, Confident, Hard-working, Active, Protective',NULL,'56 - 66','18 - 36'),
	 (38,'Belgian Tervuren','Energetic, Alert, Loyal, Intelligent, Attentive, Protective',NULL,'56 - 66','18 - 29'),
	 (41,'Bernese Mountain Dog','Affectionate, Loyal, Intelligent, Faithful',NULL,'58 - 70','29 - 54'),
	 (42,'Bichon Frise','Feisty, Affectionate, Cheerful, Playful, Gentle, Sensitive',NULL,'24 - 29','5 - 8'),
	 (43,'Black and Tan Coonhound','Easygoing, Gentle, Adaptable, Trusting, Even Tempered, Lovable',NULL,'58 - 69','29 - 45'),
	 (45,'Bloodhound','Stubborn, Affectionate, Gentle, Even Tempered',NULL,'58 - 69','36 - 50'),
	 (47,'Bluetick Coonhound','Friendly, Intelligent, Active',NULL,'53 - 69','20 - 36'),
	 (48,'Boerboel','Obedient, Confident, Intelligent, Dominant, Territorial',NULL,'56 - 69','50 - 91');
INSERT INTO dogwalkers.pasma (ID_pasma,Pasma_ime,Temperament,WikiPasmeUrl,Visina,Teza) VALUES
	 (50,'Border Collie','Tenacious, Keen, Energetic, Responsive, Alert, Intelligent',NULL,'46 - 56','14 - 20'),
	 (51,'Border Terrier','Fearless, Affectionate, Alert, Obedient, Intelligent, Even Tempered',NULL,'28 - 41','5 - 7'),
	 (53,'Boston Terrier','Friendly, Lively, Intelligent',NULL,'41 - 43','5 - 11'),
	 (54,'Bouvier des Flandres','Protective, Loyal, Gentle, Intelligent, Familial, Rational',NULL,'60 - 70','32 - 50'),
	 (55,'Boxer','Devoted, Fearless, Friendly, Cheerful, Energetic, Loyal, Playful, Confident, Intelligent, Bright, Brave, Calm',NULL,'55 - 64','23 - 32'),
	 (56,'Boykin Spaniel','Friendly, Energetic, Companionable, Intelligent, Eager, Trainable',NULL,'36 - 46','11 - 18'),
	 (57,'Bracco Italiano','Stubborn, Affectionate, Loyal, Playful, Companionable, Trainable',NULL,'55 - 67','25 - 40'),
	 (58,'Briard','Fearless, Loyal, Obedient, Intelligent, Faithful, Protective',NULL,'56 - 69','32 - 41'),
	 (59,'Brittany','Agile, Adaptable, Quick, Intelligent, Attentive, Happy',NULL,'44 - 52','14 - 20'),
	 (61,'Bull Terrier','Trainable, Protective, Sweet-Tempered, Keen, Active',NULL,'53 - 56','23 - 32');
INSERT INTO dogwalkers.pasma (ID_pasma,Pasma_ime,Temperament,WikiPasmeUrl,Visina,Teza) VALUES
	 (62,'Bull Terrier (Miniature)','Trainable, Protective, Sweet-Tempered, Keen, Active, Territorial',NULL,'25 - 36','11 - 15'),
	 (64,'Bullmastiff','Docile, Reliable, Devoted, Alert, Loyal, Reserved, Loving, Protective, Powerful, Calm, Courageous',NULL,'61 - 69','45 - 59'),
	 (65,'Cairn Terrier','Hardy, Fearless, Assertive, Gay, Intelligent, Active',NULL,'23 - 25','6 - 6'),
	 (67,'Cane Corso','Trainable, Reserved, Stable, Quiet, Even Tempered, Calm',NULL,'60 - 70','40 - 54'),
	 (68,'Cardigan Welsh Corgi','Affectionate, Devoted, Alert, Companionable, Intelligent, Active',NULL,'27 - 32','11 - 17'),
	 (69,'Catahoula Leopard Dog','Energetic, Inquisitive, Independent, Gentle, Intelligent, Loving',NULL,'51 - 66','23 - 43'),
	 (70,'Caucasian Shepherd (Ovcharka)','Alert, Quick, Dominant, Powerful, Calm, Strong',NULL,'61 - 85','36 - 45'),
	 (71,'Cavalier King Charles Spaniel','Fearless, Affectionate, Sociable, Patient, Playful, Adaptable',NULL,'30 - 33','6 - 8'),
	 (76,'Chesapeake Bay Retriever','Affectionate, Intelligent, Quiet, Dominant, Happy, Protective',NULL,'53 - 66','25 - 36'),
	 (78,'Chinese Crested','Affectionate, Sweet-Tempered, Lively, Alert, Playful, Happy',NULL,'28 - 33','5 - 6');
INSERT INTO dogwalkers.pasma (ID_pasma,Pasma_ime,Temperament,WikiPasmeUrl,Visina,Teza) VALUES
	 (79,'Chinese Shar-Pei','Suspicious, Affectionate, Devoted, Reserved, Independent, Loving',NULL,'46 - 51','20 - 27'),
	 (80,'Chinook','Friendly, Alert, Dignified, Intelligent, Calm',NULL,'56 - 66','23 - 41'),
	 (81,'Chow Chow','Aloof, Loyal, Independent, Quiet',NULL,'43 - 51','18 - 32'),
	 (84,'Clumber Spaniel','Affectionate, Loyal, Dignified, Gentle, Calm, Great-hearted',NULL,'43 - 51','25 - 39'),
	 (86,'Cocker Spaniel','Trainable, Friendly, Affectionate, Playful, Quiet, Faithful',NULL,'36 - 38','9 - 14'),
	 (87,'Cocker Spaniel (American)','Outgoing, Sociable, Trusting, Joyful, Even Tempered, Merry',NULL,'36 - 38','9 - 14'),
	 (89,'Coton de Tulear','Affectionate, Lively, Playful, Intelligent, Trainable, Vocal',NULL,'23 - 28','4 - 7'),
	 (92,'Dalmatian','Outgoing, Friendly, Energetic, Playful, Sensitive, Intelligent, Active',NULL,'48 - 58','23 - 25'),
	 (94,'Doberman Pinscher','Fearless, Energetic, Alert, Loyal, Obedient, Confident, Intelligent',NULL,'61 - 71','30 - 40'),
	 (95,'Dogo Argentino','Friendly, Affectionate, Cheerful, Loyal, Tolerant, Protective',NULL,'60 - 69','36 - 45');
INSERT INTO dogwalkers.pasma (ID_pasma,Pasma_ime,Temperament,WikiPasmeUrl,Visina,Teza) VALUES
	 (98,'Dutch Shepherd','Reliable, Affectionate, Alert, Loyal, Obedient, Trainable',NULL,'56 - 62','23 - 32'),
	 (101,'English Setter','Strong Willed, Mischievous, Affectionate, Energetic, Playful, Companionable, Gentle, Hard-working, Intelligent, Eager, People-Oriented',NULL,'61 - 64','20 - 36'),
	 (102,'English Shepherd','Kind, Energetic, Independent, Adaptable, Intelligent, Bossy',NULL,'46 - 58','20 - 30'),
	 (103,'English Springer Spaniel','Affectionate, Cheerful, Alert, Intelligent, Attentive, Active',NULL,'48 - 51','16 - 23'),
	 (104,'English Toy Spaniel','Affectionate, Reserved, Playful, Gentle, Happy, Loving',NULL,'25','4 - 6'),
	 (105,'English Toy Terrier','Stubborn, Alert, Companionable, Intelligent, Cunning, Trainable',NULL,'25 - 30','3 - 4'),
	 (107,'Eurasier','Alert, Reserved, Intelligent, Even Tempered, Watchful, Calm',NULL,'52 - 60','18 - 32'),
	 (108,'Field Spaniel','Docile, Cautious, Sociable, Sensitive, Adaptable, Familial',NULL,'43 - 46','16 - 23'),
	 (110,'Finnish Lapphund','Friendly, Keen, Faithful, Calm, Courageous',NULL,'41 - 53','15 - 24'),
	 (111,'Finnish Spitz','Playful, Loyal, Independent, Intelligent, Happy, Vocal',NULL,'39 - 51','10 - 13');
INSERT INTO dogwalkers.pasma (ID_pasma,Pasma_ime,Temperament,WikiPasmeUrl,Visina,Teza) VALUES
	 (113,'French Bulldog','Playful, Affectionate, Keen, Sociable, Lively, Alert, Easygoing, Patient, Athletic, Bright',NULL,'28 - 30','13'),
	 (114,'German Pinscher','Spirited, Lively, Intelligent, Loving, Even Tempered, Familial',NULL,'43 - 51','11 - 20'),
	 (115,'German Shepherd Dog','Alert, Loyal, Obedient, Curious, Confident, Intelligent, Watchful, Courageous',NULL,'56 - 66','23 - 41'),
	 (116,'German Shorthaired Pointer','Boisterous, Bold, Affectionate, Intelligent, Cooperative, Trainable',NULL,'53 - 64','20 - 32'),
	 (119,'Giant Schnauzer','Strong Willed, Kind, Loyal, Intelligent, Dominant, Powerful',NULL,'60 - 70','29 - 41'),
	 (120,'Glen of Imaal Terrier','Spirited, Agile, Loyal, Gentle, Active, Courageous',NULL,'32 - 36','15 - 18'),
	 (121,'Golden Retriever','Intelligent, Kind, Reliable, Friendly, Trustworthy, Confident',NULL,'55 - 61','25 - 34'),
	 (123,'Gordon Setter','Fearless, Alert, Loyal, Confident, Gay, Eager',NULL,'58 - 69','20 - 36'),
	 (124,'Great Dane','Friendly, Devoted, Reserved, Gentle, Confident, Loving',NULL,'71 - 81','50 - 86'),
	 (125,'Great Pyrenees','Strong Willed, Fearless, Affectionate, Patient, Gentle, Confident',NULL,'64 - 81','39 - 52');
INSERT INTO dogwalkers.pasma (ID_pasma,Pasma_ime,Temperament,WikiPasmeUrl,Visina,Teza) VALUES
	 (127,'Greyhound','Affectionate, Athletic, Gentle, Intelligent, Quiet, Even Tempered',NULL,'69 - 76','23 - 32'),
	 (128,'Griffon Bruxellois','Self-important, Inquisitive, Alert, Companionable, Sensitive, Watchful',NULL,'23 - 28','5'),
	 (129,'Harrier','Outgoing, Friendly, Cheerful, Sweet-Tempered, Tolerant, Active',NULL,'46 - 56','18 - 27'),
	 (130,'Havanese','Affectionate, Responsive, Playful, Companionable, Gentle, Intelligent',NULL,'22 - 29','3 - 6'),
	 (134,'Irish Setter','Affectionate, Energetic, Lively, Independent, Playful, Companionable',NULL,'61 - 69','16 - 32'),
	 (135,'Irish Terrier','Respectful, Lively, Intelligent, Dominant, Protective, Trainable',NULL,'46','11 - 12'),
	 (137,'Irish Wolfhound','Sweet-Tempered, Loyal, Dignified, Patient, Thoughtful, Generous',NULL,'76 - 89','48 - 82'),
	 (138,'Italian Greyhound','Mischievous, Affectionate, Agile, Athletic, Companionable, Intelligent',NULL,'33 - 38','3 - 7'),
	 (140,'Japanese Chin','Alert, Loyal, Independent, Intelligent, Loving, Cat-like',NULL,'20 - 28','2 - 4'),
	 (141,'Japanese Spitz','Affectionate, Obedient, Playful, Companionable, Intelligent, Proud',NULL,'30 - 38','7 - 9');
INSERT INTO dogwalkers.pasma (ID_pasma,Pasma_ime,Temperament,WikiPasmeUrl,Visina,Teza) VALUES
	 (142,'Keeshond','Agile, Obedient, Playful, Quick, Sturdy, Bright',NULL,'43 - 46','16 - 20'),
	 (144,'Komondor','Steady, Fearless, Affectionate, Independent, Gentle, Calm',NULL,'65 - 70','36 - 45'),
	 (145,'Kooikerhondje','Benevolent, Agile, Alert, Intelligent, Active, Territorial',NULL,'36 - 41','9 - 14'),
	 (147,'Kuvasz','Clownish, Loyal, Patient, Independent, Intelligent, Protective',NULL,'66 - 76','32 - 52'),
	 (149,'Labrador Retriever','Kind, Outgoing, Agile, Gentle, Intelligent, Trusting, Even Tempered',NULL,'55 - 62','25 - 36'),
	 (151,'Lagotto Romagnolo','Keen, Loyal, Companionable, Loving, Active, Trainable',NULL,'41 - 48','11 - 16'),
	 (153,'Lancashire Heeler','Clever, Friendly, Alert, Intelligent',NULL,'25 - 30','3 - 6'),
	 (155,'Leonberger','Obedient, Fearless, Loyal, Companionable, Adaptable, Loving',NULL,'65 - 80','54 - 77'),
	 (156,'Lhasa Apso','Steady, Fearless, Friendly, Devoted, Assertive, Spirited, Energetic, Lively, Alert, Obedient, Playful, Intelligent',NULL,'25 - 28','5 - 8'),
	 (161,'Maltese','Playful, Docile, Fearless, Affectionate, Sweet-Tempered, Lively, Responsive, Easygoing, Gentle, Intelligent, Active',NULL,'20 - 25','2 - 3');
INSERT INTO dogwalkers.pasma (ID_pasma,Pasma_ime,Temperament,WikiPasmeUrl,Visina,Teza) VALUES
	 (165,'Miniature American Shepherd','Energetic, Loyal, Intelligent, Trainable',NULL,'33 - 46','9 - 18'),
	 (167,'Miniature Pinscher','Clever, Outgoing, Friendly, Energetic, Responsive, Playful',NULL,'25 - 32','4 - 5'),
	 (168,'Miniature Schnauzer','Fearless, Friendly, Spirited, Alert, Obedient, Intelligent',NULL,'30 - 36','5 - 9'),
	 (171,'Newfoundland','Sweet-Tempered, Gentle, Trainable',NULL,'66 - 71','45 - 68'),
	 (172,'Norfolk Terrier','Self-confidence, Fearless, Spirited, Companionable, Happy, Lovable',NULL,'23 - 25','5 - 5'),
	 (176,'Norwich Terrier','Hardy, Affectionate, Energetic, Sensitive, Intelligent',NULL,'25','5 - 5'),
	 (177,'Nova Scotia Duck Tolling Retriever','Outgoing, Alert, Patient, Intelligent, Loving',NULL,'43 - 53','16 - 23'),
	 (178,'Old English Sheepdog','Sociable, Bubbly, Playful, Adaptable, Intelligent, Loving',NULL,'53','27 - 45'),
	 (179,'Olde English Bulldogge','Friendly, Alert, Confident, Loving, Courageous, Strong',NULL,'38 - 48','NaN'),
	 (181,'Papillon','Hardy, Friendly, Energetic, Alert, Intelligent, Happy',NULL,'20 - 28','1 - 5');
INSERT INTO dogwalkers.pasma (ID_pasma,Pasma_ime,Temperament,WikiPasmeUrl,Visina,Teza) VALUES
	 (183,'Pekingese','Opinionated, Good-natured, Stubborn, Affectionate, Aggressive, Intelligent',NULL,'15 - 23','6'),
	 (184,'Pembroke Welsh Corgi','Tenacious, Outgoing, Friendly, Bold, Playful, Protective',NULL,'25 - 30','11 - 14'),
	 (185,'Perro de Presa Canario','Strong Willed, Suspicious, Gentle, Dominant, Calm',NULL,'56 - 65','40 - 50'),
	 (188,'Pharaoh Hound','Affectionate, Sociable, Playful, Intelligent, Active, Trainable',NULL,'53 - 64','18 - 27'),
	 (189,'Plott','Bold, Alert, Loyal, Intelligent',NULL,'51 - 64','18 - 27'),
	 (193,'Pomeranian','Extroverted, Friendly, Sociable, Playful, Intelligent, Active',NULL,'20 - 30','1 - 3'),
	 (196,'Poodle (Miniature)','',NULL,'28 - 38','7 - 8'),
	 (197,'Poodle (Toy)','',NULL,'23 - 28','3 - 4'),
	 (201,'Pug','Docile, Clever, Charming, Stubborn, Sociable, Playful, Quiet, Attentive',NULL,'25 - 30','6 - 8'),
	 (204,'Puli','Energetic, Agile, Loyal, Obedient, Intelligent, Faithful',NULL,'41 - 43','11 - 16');
INSERT INTO dogwalkers.pasma (ID_pasma,Pasma_ime,Temperament,WikiPasmeUrl,Visina,Teza) VALUES
	 (205,'Pumi','Lively, Reserved, Intelligent, Active, Protective, Vocal',NULL,'38 - 47','8 - 15'),
	 (207,'Rat Terrier','Affectionate, Lively, Inquisitive, Alert, Intelligent, Loving',NULL,'25 - 33','4 - 11'),
	 (208,'Redbone Coonhound','Affectionate, Energetic, Independent, Companionable, Familial, Unflappable',NULL,'53 - 69','20 - 36'),
	 (209,'Rhodesian Ridgeback','Strong Willed, Mischievous, Loyal, Dignified, Sensitive, Intelligent',NULL,'61 - 69','34 - 36'),
	 (210,'Rottweiler','Steady, Good-natured, Fearless, Devoted, Alert, Obedient, Confident, Self-assured, Calm, Courageous',NULL,'56 - 69','34 - 50'),
	 (211,'Russian Toy','',NULL,'19 - 27','1 - 3'),
	 (212,'Saint Bernard','Friendly, Lively, Gentle, Watchful, Calm',NULL,'65 - 70','59 - 82'),
	 (213,'Saluki','Aloof, Reserved, Intelligent, Quiet',NULL,'58 - 71','16 - 29'),
	 (214,'Samoyed','Stubborn, Friendly, Sociable, Lively, Alert, Playful',NULL,'48 - 60','23 - 27'),
	 (216,'Schipperke','Fearless, Agile, Curious, Independent, Confident, Faithful',NULL,'25 - 33','5 - 7');
INSERT INTO dogwalkers.pasma (ID_pasma,Pasma_ime,Temperament,WikiPasmeUrl,Visina,Teza) VALUES
	 (218,'Scottish Deerhound','Docile, Friendly, Dignified, Gentle',NULL,'71 - 81','32 - 59'),
	 (219,'Scottish Terrier','Feisty, Alert, Independent, Playful, Quick, Self-assured',NULL,'25','8 - 10'),
	 (221,'Shetland Sheepdog','Affectionate, Lively, Responsive, Alert, Loyal, Reserved, Playful, Gentle, Intelligent, Active, Trainable, Strong',NULL,'33 - 41','14'),
	 (222,'Shiba Inu','Charming, Fearless, Keen, Alert, Confident, Faithful',NULL,'34 - 42','8 - 10'),
	 (223,'Shih Tzu','Clever, Spunky, Outgoing, Friendly, Affectionate, Lively, Alert, Loyal, Independent, Playful, Gentle, Intelligent, Happy, Active, Courageous',NULL,'20 - 28','4 - 7'),
	 (225,'Shiloh Shepherd','Outgoing, Loyal, Companionable, Gentle, Loving, Trainable',NULL,'66 - 76','54 - 64'),
	 (226,'Siberian Husky','Outgoing, Friendly, Alert, Gentle, Intelligent',NULL,'51 - 60','16 - 27'),
	 (228,'Silky Terrier','Friendly, Responsive, Inquisitive, Alert, Quick, Joyful',NULL,'23 - 25','4 - 5'),
	 (232,'Smooth Fox Terrier','Fearless, Affectionate, Alert, Playful, Intelligent, Active',NULL,'39','NaN - 8'),
	 (233,'Soft Coated Wheaten Terrier','Affectionate, Spirited, Energetic, Playful, Intelligent, Faithful',NULL,'41 - 46','14 - 18');
INSERT INTO dogwalkers.pasma (ID_pasma,Pasma_ime,Temperament,WikiPasmeUrl,Visina,Teza) VALUES
	 (235,'Spanish Water Dog','Trainable, Diligent, Affectionate, Loyal, Athletic, Intelligent',NULL,'41 - 51','14 - 23'),
	 (236,'Spinone Italiano','Docile, Friendly, Affectionate, Loyal, Patient, Gentle',NULL,'57 - 70','28 - 39'),
	 (238,'Staffordshire Bull Terrier','Reliable, Fearless, Bold, Affectionate, Loyal, Intelligent, Courageous',NULL,'36 - 41','11 - 17'),
	 (239,'Standard Schnauzer','Trainable, Good-natured, Devoted, Lively, Playful, Intelligent',NULL,'44 - 50','14 - 23'),
	 (242,'Swedish Vallhund','Fearless, Friendly, Energetic, Alert, Intelligent, Watchful',NULL,'29 - 34','9 - 14'),
	 (243,'Thai Ridgeback','Protective, Loyal, Independent, Intelligent, Loving, Familial',NULL,'51 - 61','16 - 25'),
	 (244,'Tibetan Mastiff','Strong Willed, Tenacious, Aloof, Stubborn, Intelligent, Protective',NULL,'61 - 66','39 - 64'),
	 (245,'Tibetan Spaniel','Willful, Aloof, Assertive, Independent, Playful, Intelligent, Happy',NULL,'25','4 - 7'),
	 (246,'Tibetan Terrier','Affectionate, Energetic, Amiable, Reserved, Gentle, Sensitive',NULL,'36 - 43','9 - 11'),
	 (248,'Toy Fox Terrier','Friendly, Spirited, Alert, Loyal, Playful, Intelligent',NULL,'20 - 28','2 - 4');
INSERT INTO dogwalkers.pasma (ID_pasma,Pasma_ime,Temperament,WikiPasmeUrl,Visina,Teza) VALUES
	 (250,'Treeing Walker Coonhound','Clever, Affectionate, Confident, Intelligent, Loving, Trainable',NULL,'51 - 69','20 - 36'),
	 (251,'Vizsla','Affectionate, Energetic, Loyal, Gentle, Quiet',NULL,'53 - 61','23 - 29'),
	 (253,'Weimaraner','Steady, Aloof, Stubborn, Energetic, Alert, Intelligent, Powerful, Fast',NULL,'58 - 69','25 - 41'),
	 (254,'Welsh Springer Spaniel','Stubborn, Friendly, Affectionate, Loyal, Playful, Active',NULL,'43 - 48','16 - 25'),
	 (256,'West Highland White Terrier','Hardy, Friendly, Alert, Independent, Gay, Active, Courageous',NULL,'25 - 28','7 - 10'),
	 (257,'Whippet','Friendly, Affectionate, Lively, Gentle, Intelligent, Quiet',NULL,'46 - 56','11 - 16'),
	 (258,'White Shepherd','Self-confidence, Aloof, Fearless, Alert, Companionable, Eager',NULL,'56 - 64','27 - 39'),
	 (259,'Wire Fox Terrier','Fearless, Friendly, Bold, Keen, Alert, Quick',NULL,'33 - 41','7 - 9'),
	 (260,'Wirehaired Pointing Griffon','Loyal, Gentle, Vigilant, Trainable, Proud',NULL,'51 - 61','20 - 32'),
	 (261,'Wirehaired Vizsla','',NULL,'55 - 64','20 - 29');
INSERT INTO dogwalkers.pasma (ID_pasma,Pasma_ime,Temperament,WikiPasmeUrl,Visina,Teza) VALUES
	 (262,'Xoloitzcuintli','Cheerful, Alert, Companionable, Intelligent, Protective, Calm',NULL,'25 - 58','4 - 14'),
	 (264,'Yorkshire Terrier','Bold, Independent, Confident, Intelligent, Courageous',NULL,'20 - 23','2 - 3');