name: CD for DogWalkers

on:
  push:
    branches: [production]
    paths-ignore:
      - "README.md" # Ignoriramo spremembe v dokumentaciji.
      - "docs/**" # Ignoriramo, če uveljavitev spreminja zgolj vsebino mape docs.

  release:
    branches: [production]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }} # Sets up the node environment
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install server dependencies
        working-directory: ./src/server/
        run: yarn

      - name: Running tests
        working-directory: ./src/server/
        run: yarn test
        env:
          JWT_ACCESS_SECRET: ${{ secrets.JWT_ACCESS_SECRET }}
          JWT_REFRESH_SECRET: ${{ secrets.JWT_REFRESH_SECRET }}
          GMAIL_ACCOUNT: ${{ secrets.GMAIL_ACCOUNT }}
          GMAIL_PASS: ${{ secrets.GMAIL_PASS }}
          # DB credentials for stage environment
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASS: ${{ secrets.DB_PASS }}
          DB_NAME: ${{ secrets.DB_NAME }}

          # DB credentials for stage environment
          MEMCACHIER_SERVERS: ${{ secrets.MEMCACHIER_SERVERS }}
          MEMCACHIER_USERNAME: ${{ secrets.MEMCACHIER_USERNAME }}
          MEMCACHIER_PASSWORD: ${{ secrets.MEMCACHIER_PASSWORD }}
          DogsAPIKEY: ${{ secrets.DogsAPIKEY }}

      - name: Deploy Server to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "tpo11-dogwalkers-server" #Must be unique in Heroku
          heroku_email: "martin.strekelj123@gmail.com"
          appdir: "src/server"

      - name: Deploy Client to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "tpo11-dogwalkers" #Must be unique in Heroku
          heroku_email: "martin.strekelj123@gmail.com"
          appdir: "src/web"
