# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: CI for DogWalkers

on:
  push:
    branches: [stage]
    paths-ignore:
      - "README.md" # Ignoriramo spremembe v dokumentaciji.
  pull_request:
    branches: [stage]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }} # Sets up the node environment
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install server dependencies
        working-directory: ./src/server/
        run: yarn

      - name: Running tests
        working-directory: ./src/server/
        run: yarn test
        env:
          JWT_ACCESS_SECRET: ${{ secrets.JWT_ACCESS_SECRET }}
          JWT_REFRESH_SECRET: ${{ secrets.JWT_REFRESH_SECRET }}
          GMAIL_ACCOUNT: ${{ secrets.GMAIL_ACCOUNT }}
          GMAIL_PASS: ${{ secrets.GMAIL_PASS }}
          # DB credentials for stage environment
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASS: ${{ secrets.DB_PASS }}
          DB_NAME: ${{ secrets.DB_NAME }}
